# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PlotMetrics": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Jorgvt.github.io/fancycallbacks/"

git_url = "https://github.com/Jorgvt/fancycallbacks/tree/master/"

def custom_doc_links(name): return None
